# Generated by Django 6.0.1 on 2026-05-13 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('email', 'Email Campaign'), ('social', 'Social Media'), ('sms', 'SMS Campaign'), ('event', 'Event'), ('whatsapp', 'WhatsApp Campaign'), ('referral', 'Referral Campaign'), ('seo', 'SEO Campaign')], default='email', max_length=20)),
                ('source_platform', models.CharField(blank=True, choices=[('facebook', 'Facebook Ads'), ('instagram', 'Instagram Ads'), ('google', 'Google Ads'), ('email', 'Email Campaign'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('seo', 'SEO / Organic'), ('website', 'Website'), ('direct', 'Direct')], default='website', max_length=20, null=True)),
                ('target_audience', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_team', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sent', models.IntegerField(default=0)),
                ('opened', models.FloatField(default=0.0)),
                ('clicked', models.FloatField(default=0.0)),
                ('leads_generated', models.IntegerField(default=0)),
                ('converted_deals', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('leads_count', models.IntegerField(default=0)),
                ('deals_count', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='marketing.campaign')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
