# Generated by Django 6.0.4 on 2026-04-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('Qualification', 'Qualification'), ('Needs Analysis', 'Needs Analysis'), ('Value Proposition', 'Value Proposition'), ('Identify Decision Makers', 'Identify Decision Makers'), ('Proposal/Price Quote', 'Proposal/Price Quote'), ('Negotiation/Review', 'Negotiation/Review'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost'), ('Closed Lost to Competition', 'Closed Lost to Competition')], default='Qualification', max_length=50),
        ),
    ]
