# Generated by Django 6.0.1 on 2026-04-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_deal_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='probability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='proposal_doc',
            field=models.FileField(blank=True, null=True, upload_to='proposals/'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('Qualification', 'Qualification'), ('Needs Analysis', 'Needs Analysis'), ('Value Proposition', 'Value Proposition'), ('Identify Decision Makers', 'Identify Decision Makers'), ('Proposal/Price Quote', 'Proposal/Price Quote'), ('Negotiation/Review', 'Negotiation/Review'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost'), ('Closed Lost to Competition', 'Closed Lost to Competition')], db_index=True, max_length=50),
        ),
    ]
