# Generated by Django 6.0.4 on 2026-05-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_alter_deal_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='probability',
            field=models.IntegerField(default=20, help_text='Win probability (0–100%). Auto-set from stage via pre_save signal.'),
        ),
    ]
