# Generated by Django 6.0.1 on 2026-05-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_product_remove_deal_expected_close_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
