# Generated by Django 6.0.1 on 2026-05-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_add_updated_at_and_quote_accepted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='expected_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(blank=True, default='Qualification', max_length=50, null=True),
        ),
    ]
