# Generated by Django 6.0.1 on 2026-05-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_deal_expected_close_date_deal_notes_alter_deal_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(blank=True, default='proposal', max_length=50, null=True),
        ),
    ]
