# Generated by Django 6.0.1 on 2026-05-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_deal_closed_at_deal_is_active_deal_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
