# Generated by Django 6.0.4 on 2026-05-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_product_category_product_created_at_product_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='gravity_score',
            field=models.FloatField(default=0.0, help_text='Gravity score for physics engine.'),
        ),
        migrations.AddField(
            model_name='deal',
            name='momentum',
            field=models.FloatField(default=0.0, help_text='Momentum for physics engine.'),
        ),
        migrations.AddField(
            model_name='deal',
            name='probability',
            field=models.IntegerField(default=20, help_text='Win probability (0–100%).'),
        ),
        migrations.AddField(
            model_name='deal',
            name='y_position',
            field=models.FloatField(default=0.0, help_text='Y position for physics engine.'),
        ),
    ]
