# Generated by Django 6.0.4 on 2026-05-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_deal_gravity_score_deal_momentum_deal_probability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='floating_height',
            field=models.FloatField(default=0.0, help_text='Floating height.'),
        ),
        migrations.AddField(
            model_name='deal',
            name='glow_intensity',
            field=models.FloatField(default=0.0, help_text='Glow intensity.'),
        ),
        migrations.AddField(
            model_name='deal',
            name='gravity_weight',
            field=models.FloatField(default=1.0, help_text='Weight for physics engine.'),
        ),
        migrations.AddField(
            model_name='deal',
            name='lift_force',
            field=models.FloatField(default=0.0, help_text='Lift force for physics engine.'),
        ),
        migrations.AddField(
            model_name='deal',
            name='risk_score',
            field=models.FloatField(default=0.0, help_text='Risk score.'),
        ),
    ]
