# Generated by Django 6.0.4 on 2026-05-11 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_marketing_attribution'),
        ('deals', '0014_deal_floating_height_deal_glow_intensity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_deals', to='activities.campaign'),
        ),
    ]
