# Generated by Django 6.0.1 on 2026-05-13 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0016_deal_utm_campaign_deal_utm_content_deal_utm_medium_and_more'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_deals', to='marketing.campaign'),
        ),
    ]
