# Generated by Django 6.0.4 on 2026-04-29 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('module', models.CharField(choices=[('lead', 'Lead'), ('deal', 'Deal'), ('task', 'Task'), ('contact', 'Contact'), ('project', 'Project')], max_length=50)),
                ('trigger_event', models.CharField(choices=[('create', 'On Create'), ('update', 'On Update'), ('delete', 'On Delete')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('assign_user', 'Assign User'), ('create_task', 'Create Task'), ('send_email', 'Send Email'), ('update_field', 'Update Field'), ('create_project', 'Create Project'), ('send_notification', 'Send Notification')], max_length=50)),
                ('action_data', models.JSONField(blank=True, default=dict)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('operator', models.CharField(choices=[('equals', 'Equals (=)'), ('not_equals', 'Not Equals (!=)'), ('contains', 'Contains'), ('gt', 'Greater Than (>)'), ('lt', 'Less Than (<)')], max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=20)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflows.workflow')),
            ],
        ),
    ]
