# Generated by Django 6.0.4 on 2026-04-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='module',
            field=models.CharField(choices=[('lead', 'Lead'), ('deal', 'Deal'), ('task', 'Task'), ('contact', 'Contact'), ('project', 'Project'), ('quote', 'Quote'), ('invoice', 'Invoice'), ('case', 'Support Case')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowaction',
            name='action_type',
            field=models.CharField(choices=[('assign_user', 'Assign User'), ('create_task', 'Create Task'), ('send_email', 'Send Email'), ('update_field', 'Update Field'), ('create_project', 'Create Project'), ('send_notification', 'Send Notification'), ('create_quote', 'Create Quote'), ('generate_invoice', 'Generate Invoice')], max_length=50),
        ),
    ]
