# Generated by Django 6.0.4 on 2026-05-02 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_workflow_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='workflowaction',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='workflowcondition',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='workflowlog',
            options={'ordering': ['-executed_at']},
        ),
        migrations.AddField(
            model_name='workflow',
            name='condition_logic',
            field=models.CharField(choices=[('AND', 'All conditions must match (AND)'), ('OR', 'Any condition must match (OR)')], default='AND', help_text='How multiple conditions are combined.', max_length=3),
        ),
        migrations.AddField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='assignment_type',
            field=models.CharField(choices=[('owner', 'Record Owner / Assigned To'), ('round_robin', 'Round Robin (distribute equally)'), ('manager', 'Team Manager'), ('specific_user', 'Specific User')], default='owner', help_text='How to assign the created task.', max_length=30),
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='delay_days',
            field=models.PositiveIntegerField(default=0, help_text='0 = immediate. N > 0 = schedule via Celery after N days.'),
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Execution order (lower = first)'),
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='specific_user',
            field=models.ForeignKey(blank=True, help_text="Used when assignment_type='specific_user'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowcondition',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Evaluation order (lower = first)'),
        ),
        migrations.AddField(
            model_name='workflowlog',
            name='object_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workflowlog',
            name='trigger_event',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='trigger_event',
            field=models.CharField(choices=[('create', 'On Create'), ('update', 'On Update'), ('delete', 'On Delete'), ('stage_changed', 'On Stage Changed'), ('status_changed', 'On Status Changed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowaction',
            name='action_data',
            field=models.JSONField(blank=True, default=dict, help_text='For create_task: {title, description, due_days_override}. For send_email: {to_field, subject, body}. For update_field: {field, value}.'),
        ),
        migrations.AlterField(
            model_name='workflowaction',
            name='action_type',
            field=models.CharField(choices=[('create_task', 'Create Task'), ('assign_user', 'Assign User'), ('send_email', 'Send Email'), ('update_field', 'Update Field'), ('create_project', 'Create Project'), ('send_notification', 'Send Notification'), ('create_quote', 'Create Quote'), ('generate_invoice', 'Generate Invoice')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowcondition',
            name='field_name',
            field=models.CharField(help_text="Dot-notation field path, e.g. 'status', 'value', 'contact.company'", max_length=255),
        ),
        migrations.AlterField(
            model_name='workflowcondition',
            name='operator',
            field=models.CharField(choices=[('equals', 'Equals (=)'), ('not_equals', 'Not Equals (!=)'), ('contains', 'Contains'), ('not_contains', 'Does Not Contain'), ('gt', 'Greater Than (>)'), ('gte', 'Greater Than or Equal (>=)'), ('lt', 'Less Than (<)'), ('lte', 'Less Than or Equal (<=)'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('is_empty', 'Is Empty'), ('is_not_empty', 'Is Not Empty')], default='equals', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowcondition',
            name='value',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='workflowlog',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workflowlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('partial', 'Partial (some actions failed)'), ('failure', 'Failure'), ('skipped', 'Skipped (conditions not met)')], max_length=20),
        ),
        migrations.CreateModel(
            name='RoundRobinState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_user_id', models.IntegerField(blank=True, help_text='PK of the last user who was assigned a task via round-robin.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='round_robin_state', to='workflows.workflowaction')),
            ],
        ),
    ]
