# Generated by Django 6.0.1 on 2026-05-05 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_workflow_options_alter_workflowaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowlog',
            name='execution_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='module',
            field=models.CharField(choices=[('lead', 'Lead'), ('deal', 'Deal'), ('account', 'Account'), ('task', 'Task'), ('call', 'Call'), ('meeting', 'Meeting'), ('contact', 'Contact'), ('product', 'Product'), ('quote', 'Quote'), ('invoice', 'Invoice'), ('project', 'Project'), ('case', 'Support Case')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='trigger_event',
            field=models.CharField(choices=[('on_create', 'On Create'), ('on_update', 'On Update'), ('stage_change', 'Stage Change'), ('on_task_complete', 'On Task Complete'), ('create', 'On Create (legacy)'), ('update', 'On Update (legacy)'), ('delete', 'On Delete (legacy)'), ('stage_changed', 'Stage Changed (legacy)'), ('status_changed', 'Status Changed (legacy)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowaction',
            name='action_type',
            field=models.CharField(choices=[('create_task', 'Create Task'), ('create_call', 'Create Call'), ('create_meeting', 'Create Meeting'), ('update_record', 'Update Record'), ('create_quote', 'Create Quote'), ('create_invoice', 'Create Invoice'), ('send_notification', 'Send Notification'), ('assign_user', 'Assign User (legacy)'), ('send_email', 'Send Email (legacy)'), ('update_field', 'Update Field (legacy)'), ('create_project', 'Create Project (legacy)'), ('generate_invoice', 'Generate Invoice (legacy)')], max_length=50),
        ),
        migrations.CreateModel(
            name='WorkflowActionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(db_index=True, max_length=255)),
                ('fingerprint', models.CharField(db_index=True, max_length=255)),
                ('created_object', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflows.workflowaction')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_executions', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('action', 'fingerprint')},
            },
        ),
    ]
