# Generated by Django 6.0.4 on 2026-05-05 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_workflowlog_execution_key_alter_workflow_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDebounce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(db_index=True, max_length=255)),
                ('execution_key', models.CharField(db_index=True, max_length=255)),
                ('last_executed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_executed_at'],
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='debounce_minutes',
            field=models.PositiveIntegerField(default=5, help_text='Prevent duplicate executions within N minutes for same object.'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['module', 'trigger_event', 'is_active'], name='workflows_w_module_1e1169_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowactionexecution',
            index=models.Index(fields=['workflow', 'action', 'created_at'], name='workflows_w_workflo_3effb4_idx'),
        ),
        migrations.AddField(
            model_name='workflowdebounce',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debounce_records', to='workflows.workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowdebounce',
            unique_together={('workflow', 'object_key')},
        ),
    ]
