# Generated by Django 6.0.1 on 2026-05-06 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_workflow_engine_fields'),
        ('workflows', '0005_workflowdebounce_workflow_debounce_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_task_type', models.CharField(help_text="e.g. 'call', 'meeting'", max_length=50)),
                ('trigger_outcome', models.CharField(help_text="e.g. 'interested', 'no_response'", max_length=50)),
                ('actions', models.JSONField(default=list, help_text="List of actions: [{'type': 'update_lead', 'status': 'qualified'}, ...]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='tasks.task')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='workflows.workflowrule')),
            ],
        ),
    ]
