# Generated by Django 6.0.1 on 2026-05-06 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_workflowrule_workflowexecutionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('root_event_key', models.CharField(max_length=255)),
                ('parent_chain_id', models.CharField(blank=True, max_length=100, null=True)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('module', models.CharField(max_length=50)),
                ('trigger', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=50)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='workflowlog',
            name='chain_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workflowaction',
            name='action_type',
            field=models.CharField(choices=[('create_task', 'Create Task'), ('create_call', 'Create Call'), ('create_meeting', 'Create Meeting'), ('update_record', 'Update Record'), ('create_quote', 'Create Quote'), ('create_invoice', 'Create Invoice'), ('send_notification', 'Send Notification'), ('assign_owner', 'Assign Owner'), ('assign_user', 'Assign User (legacy)'), ('send_email', 'Send Email (legacy)'), ('update_field', 'Update Field (legacy)'), ('create_project', 'Create Project (legacy)'), ('generate_invoice', 'Generate Invoice (legacy)')], max_length=50),
        ),
        migrations.CreateModel(
            name='WorkflowActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('retrying', 'Retrying'), ('skipped', 'Skipped')], max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('error_details', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowaction')),
                ('workflow_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='workflows.workflowlog')),
            ],
            options={
                'ordering': ['executed_at'],
            },
        ),
    ]
