# Generated by Django 6.0.4 on 2026-05-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_workflowchain_workflowevent_workflowlog_chain_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowaction',
            name='compensation_action',
            field=models.JSONField(blank=True, default=dict, help_text='JSON config for rollback if subsequent actions in chain fail.'),
        ),
        migrations.AddField(
            model_name='workflowactionlog',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workflowactionlog',
            name='is_compensated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowevent',
            name='source_timestamp',
            field=models.DateTimeField(blank=True, help_text='Original event timestamp', null=True),
        ),
        migrations.AddField(
            model_name='workflowevent',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Object version at time of event'),
        ),
    ]
