# Generated by Django 6.0.1 on 2026-05-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_workflowaction_compensation_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowaction',
            name='action_type',
            field=models.CharField(choices=[('create_task', 'Create Task'), ('create_call', 'Create Call'), ('create_meeting', 'Create Meeting'), ('update_record', 'Update Record'), ('create_quote', 'Create Quote'), ('create_invoice', 'Create Invoice'), ('send_notification', 'Send Notification'), ('assign_owner', 'Assign Owner'), ('close_open_tasks', 'Close Open Tasks'), ('assign_user', 'Assign User (legacy)'), ('send_email', 'Send Email (legacy)'), ('update_field', 'Update Field (legacy)'), ('create_project', 'Create Project (legacy)'), ('generate_invoice', 'Generate Invoice (legacy)')], max_length=50),
        ),
    ]
