# Generated by Django 6.0.1 on 2026-05-16 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_alter_workflowaction_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_active_version',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='parent_workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='workflows.workflow'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='workflow',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='branch_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='parent_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_actions', to='workflows.workflowaction'),
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='position_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='position_y',
            field=models.FloatField(default=0.0),
        ),
    ]
