# Generated by Django 6.0.1 on 2026-05-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('connected', 'Connected'), ('qualified', 'Qualified'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
