# Generated by Django 6.0.4 on 2026-05-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quote_delivery_terms_quote_notes_quote_payment_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
