# Generated by Django 6.0.4 on 2026-05-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_alter_activity_content_type_alter_activity_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('note', 'Note'), ('update', 'Update'), ('reminder', 'Reminder')], default='note', max_length=20),
        ),
    ]
