# Generated by Django 6.0.4 on 2026-05-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('update', 'Update'), ('completed', 'Completed'), ('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('note', 'Note'), ('reminder', 'Reminder')], default='note', max_length=20),
        ),
    ]
