# Generated by Django 6.0.1 on 2026-05-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_rename_created_by_call_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
