# Generated by Django 6.0.1 on 2026-05-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_call_company_call_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('scheduled', 'Scheduled')], default='outbound', max_length=20),
        ),
        migrations.AlterField(
            model_name='call',
            name='outcome',
            field=models.CharField(choices=[('interested', 'Interested'), ('no_answer', 'No Answer'), ('not_interested', 'Not Interested'), ('voicemail', 'Voicemail'), ('connected', 'Connected'), ('follow_up', 'Follow-up Required'), ('pending', 'Pending')], default='connected', max_length=30),
        ),
    ]
