# Generated by Django 6.0.1 on 2026-05-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_alter_call_direction_alter_call_outcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='call_date',
        ),
        migrations.RemoveField(
            model_name='call',
            name='company',
        ),
        migrations.RemoveField(
            model_name='call',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='call',
            name='created_from_task',
        ),
        migrations.AddField(
            model_name='call',
            name='call_status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='call',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='outbound', max_length=20),
        ),
        migrations.AlterField(
            model_name='call',
            name='outcome',
            field=models.CharField(choices=[('connected', 'Connected'), ('no_response', 'No Response'), ('not_interested', 'Not Interested'), ('pending', 'Pending')], default='pending', max_length=30),
        ),
    ]
