# Generated by Django 6.0.1 on 2026-05-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_remove_call_call_date_remove_call_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
