# Generated by Django 6.0.4 on 2026-05-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_meeting_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
