# Generated by Django 6.0.4 on 2026-05-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_campaign_budget_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='actual_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campaign',
            name='assigned_team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='converted_deals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='expected_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campaign',
            name='leads_generated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='source_platform',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook Ads'), ('instagram', 'Instagram Ads'), ('google', 'Google Ads'), ('email', 'Email Campaign'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('seo', 'SEO / Organic'), ('website', 'Website'), ('direct', 'Direct')], default='website', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('email', 'Email Campaign'), ('social', 'Social Media'), ('sms', 'SMS Campaign'), ('event', 'Event'), ('whatsapp', 'WhatsApp Campaign'), ('referral', 'Referral Campaign'), ('seo', 'SEO Campaign')], default='email', max_length=20),
        ),
    ]
