# Generated by Django 6.0.1 on 2026-05-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_marketing_attribution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
