# Generated by Django 6.0.4 on 2026-05-02 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
        ('workflows', '0003_alter_workflow_options_alter_workflowaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date', '-priority']},
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='source_object_id',
            field=models.CharField(blank=True, default='', help_text='PK of the triggering record (lead, deal, etc.).', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='source_workflow',
            field=models.ForeignKey(blank=True, help_text='Populated when this task was auto-created by a workflow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='workflows.workflow'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
