# Generated by Django 6.0.4 on 2026-05-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='update_count',
            field=models.IntegerField(default=0),
        ),
    ]
