# Generated by Django 6.0.4 on 2026-05-04 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_add_probability_and_owner_fields'),
        ('leads', '0004_lead_next_action_alter_lead_status'),
        ('tasks', '0006_task_update_count'),
        ('workflows', '0003_alter_workflow_options_alter_workflowaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['lead', 'title', 'is_active'], name='tasks_task_lead_id_5fd2ac_idx'),
        ),
    ]
