# Generated by Django 6.0.1 on 2026-05-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_tasks_task_lead_id_5fd2ac_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(default='Manual', help_text='Manual / Automation', max_length=50),
        ),
    ]
