# Generated by Django 6.0.1 on 2026-05-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_completed_at_task_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='current_step',
            field=models.CharField(default='Initial Call', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='next_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='steps',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
