# Generated by Django 6.0.1 on 2026-05-04 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_add_probability_and_owner_fields'),
        ('leads', '0004_lead_next_action_alter_lead_status'),
        ('tasks', '0010_task_current_step_task_next_action_task_steps'),
        ('workflows', '0003_alter_workflow_options_alter_workflowaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('status', 'completed'), _negated=True), ('lead__isnull', False)), fields=('lead',), name='unique_active_task_per_lead'),
        ),
    ]
