# Generated by Django 6.0.1 on 2026-05-05 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_unique_active_task_per_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='unique_active_task_per_lead',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_lead_id_9b276f_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='call_duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds (if Call)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='call_outcome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='meeting_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='meeting_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='current_step',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='source_object_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='steps',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('call', 'Call 📞'), ('meeting', 'Meeting 🧑💼'), ('follow_up', 'Follow-Up'), ('proposal', 'Proposal')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='task',
            name='source',
        ),
        migrations.RemoveField(
            model_name='task',
            name='source_workflow',
        ),
        migrations.RemoveField(
            model_name='task',
            name='update_count',
        ),
    ]
