# Generated by Django 6.0.1 on 2026-05-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_account_task_contact_task_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('call', 'Call 📞'), ('meeting', 'Meeting 🧑💼'), ('follow_up', 'Follow-Up'), ('proposal', 'Proposal'), ('todo', 'To-Do'), ('email', 'Email')], default='todo', max_length=20),
        ),
    ]
