# Generated by Django 6.0.1 on 2026-05-07 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_workflow_engine_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='outcome',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('no_response', 'No Response'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('follow_up', 'Follow-up Required')], max_length=50, null=True),
        ),
    ]
