# Generated by Django 6.0.1 on 2026-05-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_task_active_by_alter_task_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='outcome',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('no_response', 'No Response'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('follow_up', 'Follow-up Required'), ('connected', 'Connected')], max_length=50, null=True),
        ),
    ]
