# Generated by Django 6.0.1 on 2026-05-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_task_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='outcome',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('no_response', 'No Response'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('follow_up', 'Follow-up Required'), ('connected', 'Connected'), ('sent', 'Proposal Sent'), ('negotiating', 'Customer Negotiating'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revision', 'Need Revision'), ('Proposal/Price Quote', 'Proposal/Price Quote'), ('Negotiation/Review', 'Negotiation/Review'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost'), ('Closed Lost to Competition', 'Closed Lost to Competition'), ('Qualification', 'Qualification'), ('Needs Analysis', 'Needs Analysis'), ('Value Proposition', 'Value Proposition'), ('Identify Decision Makers', 'Identify Decision Makers')], max_length=50, null=True),
        ),
    ]
