# Generated by Django 6.0.4 on 2026-05-09 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_account_remove_contact_company_and_more'),
        ('deals', '0014_deal_floating_height_deal_glow_intensity_and_more'),
        ('leads', '0010_alter_lead_status'),
        ('tasks', '0018_alter_task_outcome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('call', 'Call 📞'), ('meeting', 'Meeting 🧑💼'), ('discovery_meeting', 'Discovery Meeting'), ('demo_meeting', 'Demo Meeting'), ('proposal_meeting', 'Proposal Meeting'), ('follow_up', 'Follow-Up'), ('proposal', 'Proposal'), ('todo', 'To-Do'), ('email', 'Email')], default='todo', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('lead', 'task_type'), name='unique_active_task_per_stage_per_lead'),
        ),
    ]
