# Generated by Django 6.0.4 on 2026-05-11 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_marketing_attribution'),
        ('tasks', '0019_alter_task_task_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='activities.campaign'),
        ),
    ]
