# Generated by Django 6.0.1 on 2026-05-13 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('tasks', '0021_task_milestone_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='marketing.campaign'),
        ),
    ]
