"""
Django settings for crm_backend project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=&!&ql7xz%((qafc8t^su09+xnh50)88$l10@k@$&l&)h2pgsp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',
    
    # Third party apps
    'channels',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    
    # Local apps
    'users',
    'leads',
    'contacts',
    'deals',
    'tasks',
    'activities',
    'projects',
    'workflows',
    'quotes',
    'invoices',
    'support',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'tasks.middleware.CurrentUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crm_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm_backend.wsgi.application'
ASGI_APPLICATION = 'crm_backend.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

CORS_ALLOW_ALL_ORIGINS = True

# Email Configuration
# ──────────────────────────────────────────────────────────────────────────────
# Set USE_SMTP=true in your environment (or .env file) to activate real SMTP delivery.
# For Gmail: use an App Password (not your normal password).
# For SendGrid: set EMAIL_HOST_USER='apikey' and EMAIL_HOST_PASSWORD=<your-api-key>
#
# Example environment variables:
#   EMAIL_HOST=smtp.gmail.com
#   EMAIL_PORT=587
#   EMAIL_HOST_USER=youraddress@gmail.com
#   EMAIL_HOST_PASSWORD=your_app_password
#   DEFAULT_FROM_EMAIL=youraddress@gmail.com
#   USE_SMTP=true
# ──────────────────────────────────────────────────────────────────────────────
_use_smtp = os.getenv('USE_SMTP', 'false').lower() == 'true'

if _use_smtp:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    # Development: prints emails to the Django terminal (no delivery)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST          = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT          = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS       = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_HOST_USER     = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL  = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@crm.example.com')

# ===========================================================================
# Logging — structured output for Django, Celery, and Workflow engine
# ===========================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        # Django request/server logs
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # All workflow-related modules — set to DEBUG to see every step
        'workflows': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # CRM app modules
        'leads':    {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'deals':    {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'tasks':    {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'contacts': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        # Celery internals
        'celery':   {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'celery.task': {'handlers': ['console'], 'level': 'DEBUG', 'propagate': False},
    },
}

# ===========================================================================
# Celery Configuration
# ===========================================================================
import os as _os

_redis_url = _os.getenv('REDIS_URL', 'redis://localhost:6379/0')

CELERY_BROKER_URL          = _redis_url
CELERY_RESULT_BACKEND      = _redis_url

# Serialization — must whitelist both for result backend
CELERY_ACCEPT_CONTENT      = ['json']
CELERY_TASK_SERIALIZER     = 'json'
CELERY_RESULT_SERIALIZER   = 'json'

# Timezone — keep consistent with Django
CELERY_TIMEZONE            = TIME_ZONE
CELERY_ENABLE_UTC          = True

# Reliability
CELERY_ACKS_LATE           = True          # Re-queue if worker dies mid-task
CELERY_TASK_REJECT_ON_WORKER_LOST = True   # Reject (not ack) on hard crash
CELERY_TASK_TRACK_STARTED  = True          # Mark tasks STARTED in result backend

# Result expiry — don't pile up result rows forever
CELERY_RESULT_EXPIRES      = 60 * 60 * 24  # 24 hours

# ---------------------------------------------------------------------------
# DEV FALLBACK: set CELERY_TASK_ALWAYS_EAGER=true in env to run tasks
# synchronously without a worker (useful for testing without Redis).
# ---------------------------------------------------------------------------
_always_eager = _os.getenv('CELERY_TASK_ALWAYS_EAGER', 'false').lower() == 'true'
CELERY_TASK_ALWAYS_EAGER            = _always_eager
CELERY_TASK_EAGER_PROPAGATES        = _always_eager  # Surface exceptions in eager mode

# ===========================================================================
# Celery Beat — Periodic Task Schedule (SLA & Reconciliation)
# ===========================================================================
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # SLA enforcement: escalate overdue tasks every 30 minutes
    'escalate-overdue-tasks': {
        'task': 'tasks.tasks.escalate_overdue_tasks',
        'schedule': 30 * 60,  # 30 minutes in seconds
        'options': {'expires': 25 * 60},  # expire if not consumed within 25 min
    },
    # Lead-task reconciliation: run every 5 minutes
    'reconcile-lead-tasks': {
        'task': 'tasks.tasks.reconcile_lead_tasks',
        'schedule': 5 * 60,  # 5 minutes in seconds
        'options': {'expires': 4 * 60},
    },
}

