# Generated by Django 6.0.4 on 2026-04-29 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='quotes.quote'),
        ),
    ]
