# Generated by Django 6.0.4 on 2026-05-11 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_service_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='duplicate_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_references', to='support.case'),
        ),
        migrations.AddField(
            model_name='case',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='last_customer_reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_cases', to='support.case'),
        ),
        migrations.AddField(
            model_name='case',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
