# Generated by Django 6.0.1 on 2026-05-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_next_action_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('connected', 'Connected'), ('qualified', 'Qualified'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
