# Generated by Django 6.0.1 on 2026-05-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('attempted', 'Attempted to Contact'), ('connected', 'Connected / Follow-up'), ('meeting', 'Meeting Scheduled'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
