# Generated by Django 6.0.1 on 2026-05-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_remove_lead_next_action_remove_lead_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='deal_required',
            field=models.BooleanField(default=False, help_text='Set to True after successful meeting until deal is created.'),
        ),
    ]
