# Generated by Django 6.0.1 on 2026-05-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_deal_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='deal_required_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when deal became required.', null=True),
        ),
    ]
