# Generated by Django 6.0.4 on 2026-05-11 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_marketing_attribution'),
        ('leads', '0010_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='activities.campaign'),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google Ads'), ('website', 'Website'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('direct', 'Direct Call'), ('email', 'Email Campaign'), ('seo', 'SEO / Organic'), ('other', 'Other')], default='other', max_length=20, null=True),
        ),
    ]
