# Generated by Django 6.0.1 on 2026-05-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_marketing_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='first_touch_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='latest_touch_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
