# Generated by Django 6.0.1 on 2026-05-13 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_first_touch_source_lead_latest_touch_source_and_more'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='marketing.campaign'),
        ),
    ]
