# Generated by Django 6.0.1 on 2026-05-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_alter_lead_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google Ads'), ('website', 'Website'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('linkedin', 'LinkedIn'), ('direct', 'Direct Call'), ('email', 'Email Campaign'), ('seo', 'SEO / Organic'), ('other', 'Other')], default='other', max_length=20, null=True),
        ),
    ]
