# Generated by Django 6.0.1 on 2026-05-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auditlog_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='scope',
            field=models.CharField(choices=[('own', 'Own Records Only'), ('team', 'Team Records'), ('global', 'Global Access')], default='own', max_length=20),
        ),
    ]
