# Generated by Django 6.0.1 on 2026-05-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_role_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_password_length', models.PositiveIntegerField(default=8)),
                ('require_special_chars', models.BooleanField(default=True)),
                ('require_numbers', models.BooleanField(default=True)),
                ('require_uppercase', models.BooleanField(default=True)),
                ('password_expiry_days', models.PositiveIntegerField(default=90)),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30)),
                ('enforce_2fa_globally', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Security Policies',
            },
        ),
    ]
