# Generated by Django 6.0.1 on 2026-05-16 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_securitypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='impersonated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonated_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
