# Generated by Django 6.0.1 on 2026-05-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auditlog_impersonated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
    ]
